# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "trunk" ]

jobs:
  build-unix:
    strategy:
      matrix:
        os: [ macos-14,macos-11,ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - uses: actions/checkout@v3
    - name: Set os/arch environment variables
      run: |
        echo "os=${RUNNER_OS}" >> $GITHUB_ENV
        echo "arch=${RUNNER_ARCH}" >> $GITHUB_ENV
    - name: Set up JDK 17
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '17'
        distribution: 'graalvm'
        cache: maven
    - id: version
      run: echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> "$GITHUB_OUTPUT"
    - name: Package
      run: mvn -B package -Pnative -Pdep-check
    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: pace-cli-${{ env.os }}-${{ env.arch }}
        path: "pace-cli"

  release:
    needs: 
      - build-unix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - run: mkdir release
      - run: zip -r release/pace-cli-Linux-X64-${{ needs.build-unix.outputs.version }}.zip pace-cli-Linux-X64 
      - run: zip -r release/pace-cli-macOS-ARM64-${{ needs.build-unix.outputs.version }}.zip pace-cli-macOS-ARM64 
      - run: zip -r release/pace-cli-macOS-X64-${{ needs.build-unix.outputs.version }}.zip pace-cli-macOS-X64
      - name: Update branch release
        uses: eine/tip@master
        with:
          tag: ${{ github.ref_name }}-latest
          rm: true
          token: ${{ secrets.RELEASE_PAT }}
          files: release/*
    
