# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "trunk" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '17'
        distribution: 'graalvm'
        cache: maven
    - name: Package
      run: mvn -B package -DskipTests
    - name: Test
      run: mvn -B test
    - name: Verify
      run: mvn -B verify -DskipTests
    - id: version
      run: echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> "$GITHUB_OUTPUT"
    - name: Upload Build Resources
      uses: actions/upload-artifact@v4
      with:
        name: build-resources
        path: "."
  
  osx-arm64:
    needs: build
    runs-on: macos-14
    steps:
    - name: Set up JDK 17
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '17'
        distribution: 'graalvm'
    - name: Download Resources
      uses: actions/download-artifact@v4
      with:
        name: build-resources
    - name: Build Executable
      run: mvn native:compile
    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: pace-cli-mac-arm64
        path: "pace-cli/target/pace-cli"
        
  release:
    needs: 
      - build
      - osx-arm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - run: mkdir release
      - run: zip -r release/pace-cli-mac-arm64-${{ needs.build.outputs.version }}.zip pace-cli-mac-arm64
      - name: Update branch release
        uses: eine/tip@master
        with:
          tag: ${{ github.ref_name }}-latest
          rm: true
          token: ${{ secrets.RELEASE_PAT }}
          files: release/*
    
